krypton: &krypton Monaspace Krypton:style=bold:pixelsize = 13
# bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}
bg_default: &bg_default {background: {color: 81A1C1ff}}
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

bar:
  height: 25
  location: top
  layer: top
  spacing: 5
  margin: 5
  foreground: ffffffff
  background: '00000066'

  # border:
  #   width: 1
  #   color: 999999cc
  #   margin: 5
  #   top-margin: 0

  # font: Monaspace Krypton:style=bold:pixelsize = 13
  font: *krypton

  left:
  - clock:
      content:
      - string:
          text: '{date} {time}'
      time-format: '%H:%M %Z'
  # - clock:
  #    time-format: "%H:%M %Z"
  #    content:
  #      - string: {text: , font: *krypton}
  #      - string: {text: "{date}", right-margin: 5}
  #      - string: {text: , font: *krypton}
  #      - string: {text: "{time}"}

  center:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: "{id}", font: *krypton}}
              conditions:
                id == 11: {string: {text: "work", font: *krypton}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  foreground: 81A1C1ff
                  # deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  # deco: {underline: {size: 3, color: ea6962ff}}

    # - foreign-toplevel:
    #     content:
    #       map:
    #         conditions:
    #           ~activated: {empty: {}}
    #           activated:
    #             - string: {text: "{app-id}", foreground: ffa0a0ff}
    #             - string: {text: ": {title}"}
    # - mpd:
    #     host: /run/mpd/socket
    #     anchors:
    #       list: &artist_album_title
    #         spacing: 0
    #         items:
    #           - map:
    #               conditions:
    #                 state == playing: {string: {text: "{artist}"}}
    #                 state == paused: {string: {text: "{artist}", foreground: ffffff66}}
    #           - string: {text: " | ", foreground: ffffff66}
    #           - map:
    #               conditions:
    #                 state == playing: {string: {text: "{album}"}}
    #                 state == paused: {string: {text: "{album}", foreground: ffffff66}}
    #           - string: {text: " | ", foreground: ffffff66}
    #           - map:
    #               conditions:
    #                 state == playing: {string: {text: "{title}", foreground: ffa0a0ff}}
    #                 state == paused: {string: {text: "{title}", foreground: ffffff66}}
    #
    #     content:
    #       map:
    #         margin: 10
    #         conditions:
    #           state == offline: {string: {text: offline, foreground: ff0000ff}}
    #           state == stopped: {string: {text: stopped}}
    #           state == paused: {list: *artist_album_title}
    #           state == playing: {list: *artist_album_title}
    
  right:
    - removables:
        anchors:
          drive: &drive { text: 󱊞, font: *krypton}
          optical: &optical {text: 󰗮, font: *krypton}
        spacing: 5
        content:
          map:
            conditions:
              ~mounted:
                map:
                  on-click: udisksctl mount -b {device}
                  conditions:
                    ~optical: [{string: *drive}, {string: {text: "{label}"}}]
                    optical: [{string: *optical}, {string: {text: "{label}"}}]
              mounted:
                map:
                  on-click: udisksctl unmount -b {device}
                  conditions:
                    ~optical:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    optical:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}
    # - sway-xkb:
    #     identifiers: [1:1:AT_Translated_Set_2_keyboard]
    #     content:
    #       - string: {text: , font: *krypton}
    #       - string: {text: "{layout}"}
    - network:
        content:
          map:
            default: {empty: {}}
            conditions:
              name == enp1s0:
                map:
                  conditions:
                    ~carrier: {empty: {}}
                    carrier:
                      map:
                        default: {string: {text: , font: *krypton, foreground: ffffff66}}
                        conditions:
                          state == up && ipv4 != "": {string: {text: , font: *krypton}}
    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp2s0:
                map:
                  default: {string: {text: , font: *krypton, foreground: ffffff66}}
                  conditions:
                    state == down: {string: {text: , font: *krypton, foreground: ff0000ff}}
                    state == up:
                      map:
                        default:
                          - string: {text: , font: *krypton}
                          - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s"}

                        conditions:
                          ipv4 == "":
                            - string: {text: , font: *krypton, foreground: ffffff66}
                            - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s", foreground: ffffff66}
    - alsa:
        card: hw:PCH
        mixer: Master
        content:
          map:
            conditions:
              ~online: {string: {text: , font: *krypton, foreground: ff0000ff}}
              online:
                map:
                  on-click: /bin/sh -c "amixer -q sset Speaker unmute && amixer -q sset Headphone unmute && amixer -q sset Master toggle"
                  conditions:
                    muted: {string: {text: 󰝟, font: *krypton}}
                    ~muted:
                      - ramp:
                          tag: percent
                          items:
                            - string: {text: 󰕿, font: *krypton}
                            - string: {text: 󰖀, font: *krypton}
                            - string: {text: 󰕾, font: *krypton}
                      - string: {text: " {percent}%", font: *krypton}

    - backlight:
        name: intel_backlight
        content: [ string: {text: , font: *krypton}, string: {text: "{percent}%"}]
    - battery:
        name: BAT0
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff, font: *krypton}
                      - string: {text: , foreground: ffa600ff, font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                - string: {text: " {capacity}%"}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 00ff00ff, font: *krypton}
                - string: {text: "{capacity}%"}
                # - string: {text: "{capacity}% {estimate}"}
              state == full:
                - string: {text: , foreground: 00ff00ff, font: *krypton}
                - string: {text: "{capacity}%"}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff, font: *krypton}
                      - string: {text: , foreground: ffa600ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                      - string: {text: , foreground: 00ff00ff, font: *krypton}
                - string: {text: "{capacity}%"}
    # - label:
    #     content:
    #       string:
    #         on-click: systemctl poweroff
    #         text: 
    #         font: *krypton
